//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messaging.Msmq {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Messaging.Msmq.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction is already initialized....
        /// </summary>
        internal static string MsmqHelper_BeginTransaction_Transaction_is_already_initialized___ {
            get {
                return ResourceManager.GetString("MsmqHelper_BeginTransaction_Transaction_is_already_initialized___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use BeginTransaction before committing the transaction..
        /// </summary>
        internal static string MsmqHelper_CommitTransaction_Please_use_BeginTransaction_before_committing_the_transaction {
            get {
                return ResourceManager.GetString("MsmqHelper_CommitTransaction_Please_use_BeginTransaction_before_committing_the_tr" +
                        "ansaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use BeginTransaction before sending the message..
        /// </summary>
        internal static string MsmqHelper_SendMessage_Please_use_BeginTransaction_before_sending_the_message {
            get {
                return ResourceManager.GetString("MsmqHelper_SendMessage_Please_use_BeginTransaction_before_sending_the_message", resourceCulture);
            }
        }
    }
}
